default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Root@123

development:
  <<: *default
  database: parking_lot_development

test:
  <<: *default
  database: parking_lot_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: parking_lot_production
  username: parking_lot
  password: <%= ENV["ACCOUNT_API_DATABASE_PASSWORD"] %>
